# Cloud Run Build YAML
# Demo a change

#Build Docker image
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/img-pythondb:latest", "."]
  

#Push Docker Image --
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/img-pythondb:latest"]

  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=nikhil-deployment.yaml
    - --image= gcr.io/$PROJECT_ID/img-pythondb:latest
    - --location=us-central1-c
    - --cluster=private-cluster

options:
  logging: CLOUD_LOGGING_ONLY
