apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: pythondb
build:
  artifacts:
    - image: gcr.io/cloudsql-docker/gce-proxy
      docker:
        dockerfile: Dockerfile
    - image: gcr.io/rb-munish-playground/nikhil
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
      - db-secrets.yaml
      - nikhil-deployment.yaml
      - nikhil-services.yaml
